const t = (value, label = value, description = "") => ({ value, label, description });

export const VOCABULARY = {
  prefix: {
    system: [],
    theme: [
      t("light", "light", "Light theme"),
      t("dark", "dark", "Dark theme"),
      t("hc", "High contrast", "High contrast theme"),
    ],
    role: [],
  },

  primitive: {
    properties: [
      t("color", "color", "Color values (hues, shades, tints)"),
      t("dimension", "dimension", "Measurement values (literal sizes/lengths)"),
      t("opacity", "opacity", "Opacity values (transparency levels)"),
      t("shadow", "shadow", "Shadow effect primitives (per-attribute values)"),
      t("blur", "blur", "Blur effect values (backdrop, filter)"),
      t("fontFamily", "fontFamily", "Font family primitives (typeface families/stacks)"),
      t("fontWeight", "fontWeight", "Font weight values (text thickness)"),
      t("textCase", "textCase", "Text casing values"),
      t("textDecoration", "textDecoration", "Text decoration values"),
      t("fontSize", "fontSize", "Font size values (text sizing)"),
      t("lineHeight", "lineHeight", "Line height values (text line spacing)"),
      t("letterSpacing", "letterSpacing", "Letter spacing values (character spacing)"),
      t("duration", "duration", "Animation duration values"),
      t("easing", "easing", "Animation easing curves"),
      t("layer", "layer", "Z-index layer values"),
    ],
    hues: [
      t("white", "white", "White hue"),
      t("black", "black", "Black hue"),
      t("gray", "gray", "Neutral gray hue"),
      t("blue", "blue", "Blue hue"),
      t("red", "red", "Red hue"),
      t("yellow", "yellow", "Yellow hue"),
      t("green", "green", "Green hue"),
      t("cyan", "cyan", "Cyan hue"),
      t("indigo", "indigo", "Indigo hue"),
      t("orange", "orange", "Orange hue"),
      t("pink", "pink", "Pink hue"),
      t("purple", "purple", "Purple hue"),
      t("teal", "teal", "Teal hue"),
      t("shamrock", "shamrock", "Shamrock hue"),
      t("olive", "olive", "Olive hue"),
      t("rose", "rose", "Rose hue"),
      t("violet", "violet", "Violet hue"),
    ],
    dimensionTypes: [
      t("space", "space", "Spacing values (margins, padding, gaps)"),
      t("size", "size", "Size values (dimensions, widths, heights)"),
      t("radius", "radius", "Corner rounding values"),
      t("stroke-width", "stroke-width", "Stroke thickness values (borders, rings)"),
      t("breakpoint", "breakpoint", "Responsive breakpoint thresholds"),
    ],
    shadowAttributes: [
      t("offset-x", "offset-x", "Horizontal shadow offset"),
      t("offset-y", "offset-y", "Vertical shadow offset"),
      t("blur", "blur", "Shadow blur radius"),
      t("spread", "spread", "Shadow spread radius"),
    ],
    fontFamilyGroups: [
      t("system", "system", "System or default font stacks"),
      t("brand", "brand", "Brand font stacks"),
    ],
    fontFamilyNames: {
      system: [
        t("sans", "sans", "Default sans-serif family/stack"),
        t("serif", "serif", "Serif family/stack"),
        t("mono", "mono", "Monospace family/stack"),
      ],
      brand: [
        t("brand-sans", "brand-sans", "Brand sans family/stack"),
        t("brand-serif", "brand-serif", "Brand serif family/stack"),
        t("optimistic-vf", "optimistic-vf", "Brand variable font family/stack"),
      ],
    },
    easing: [
      t("standard", "standard", "Default motion curve"),
      t("emphasized", "emphasized", "Stronger curve for prominent motion"),
      t("decelerate", "decelerate", "Ease-out curve (enter/expand)"),
      t("accelerate", "accelerate", "Ease-in curve (exit/collapse)"),
      t("linear", "linear", "Linear curve"),
    ],
    textCase: [
      t("none", "none", "No forced casing"),
      t("uppercase", "uppercase", "Uppercase transform"),
      t("lowercase", "lowercase", "Lowercase transform"),
      t("capitalize", "capitalize", "Capitalize words"),
    ],
    textDecoration: [
      t("none", "none", "No decoration"),
      t("underline", "underline", "Underline text"),
      t("line-through", "line-through", "Strikethrough text"),
    ],
  },

  semantic: {
    roles: [
      t("surface", "surface", "Surfaces and backgrounds that content sits on"),
      t("content", "content", "Text and icon content that appears on surfaces"),
      t("separator", "separator", "Dividers and borders that separate content"),
      t("action", "action", "Interactive elements like buttons and controls"),
      t("link", "link", "Hyperlink elements"),
      t("focus", "focus", "Focus indicators and outlines"),
      t("status", "status", "Status indicators (positive, negative, warning, info)"),
      t("toggle", "toggle", "Toggle switch controls (on/off states)"),
      t("range", "range", "Range and slider controls"),
      t("overlay", "overlay", "Overlay layers (modals, popovers, scrims)"),
      t("accent", "accent", "Accent colors for brand emphasis"),
      t("constant", "constant", "Constant values that never theme"),
      t("type", "type", "Typography styles and properties"),
      t("space", "space", "Semantic spacing patterns"),
      t("size", "size", "Semantic sizing patterns"),
      t("radius", "radius", "Semantic corner radius patterns"),
      t("border-width", "border-width", "Semantic border width patterns"),
      t("shadow", "shadow", "Semantic shadow effect patterns"),
    ],
    elementsByRole: {
      surface: [
        t("background", "background", "Base background surfaces"),
        t("raised", "raised", "Elevated surfaces (cards, panels above base)"),
        t("sunken", "sunken", "Recessed surfaces (inputs, depressed areas)"),
        t("container", "container", "Default content containers"),
        t("elevated", "elevated", "Highly elevated floating surfaces"),
        t("canvas", "canvas", "Main content area surfaces"),
        t("overlay", "overlay", "Surface overlays"),
        t("shadow", "shadow", "Surface shadow treatments"),
      ],
      content: [
        t("text", "text", "Text content"),
        t("icon", "icon", "Icon content"),
        t("link", "link", "Link content"),
      ],
      separator: [
        t("divider", "divider", "Dividers between sections"),
        t("border", "border", "Structural borders and frames"),
        t("outline", "outline", "Structural outlines"),
        t("container-border", "container-border", "Borders for containers or panels"),
      ],
      action: [
        t("background", "background", "Action backgrounds"),
        t("text", "text", "Action text"),
        t("border", "border", "Action borders"),
        t("icon", "icon", "Action icons"),
        t("on-background", "on-background", "Foreground on action backgrounds"),
        t("link", "link", "Action links"),
      ],
      link: [
        t("default", "default", "Standard link styling"),
        t("subtle", "subtle", "Lower-emphasis link styling"),
      ],
      focus: [
        t("ring", "ring", "Focus ring indicator"),
        t("outline", "outline", "Focus outline indicator"),
        t("halo", "halo", "Outer focus glow"),
        t("inner", "inner", "Inner focus indicator"),
      ],
      status: [
        t("positive", "positive", "Positive or success status"),
        t("negative", "negative", "Negative or error status"),
        t("warning", "warning", "Warning status"),
        t("info", "info", "Informational status"),
      ],
      toggle: [
        t("background", "background", "Toggle backgrounds"),
        t("icon", "icon", "Toggle icons"),
      ],
      range: [
        t("track", "track", "Range track"),
        t("fill", "fill", "Range fill"),
        t("thumb", "thumb", "Range thumb"),
      ],
      overlay: [
        t("scrim", "scrim", "Scrim overlay"),
        t("backdrop", "backdrop", "Backdrop overlay"),
      ],
      accent: [
        t("background", "background", "Accent backgrounds"),
        t("text", "text", "Accent text"),
      ],
      constant: [t("color", "color", "Constant colors that never theme")],
      type: [
        t("body", "body", "Body text style"),
        t("heading", "heading", "Heading text style"),
        t("label", "label", "Label text style"),
        t("mono", "mono", "Monospace text style"),
      ],
      space: [
        t("layout", "layout", "Layout-level spacing"),
        t("component", "component", "Component-level spacing"),
        t("content", "content", "Content-level spacing"),
      ],
      size: [
        t("icon", "icon", "Icon sizing"),
        t("control", "control", "Control sizing"),
        t("container", "container", "Container sizing"),
      ],
      radius: [
        t("surface", "surface", "Surface corner radius"),
        t("control", "control", "Control corner radius"),
        t("card", "card", "Card corner radius"),
        t("avatar", "avatar", "Avatar corner radius"),
      ],
      "border-width": [
        t("default", "default", "Default border width"),
        t("divider", "divider", "Divider border width"),
        t("focus", "focus", "Focus indicator border width"),
      ],
      shadow: [
        t("none", "none", "No shadow effect"),
        t("subtle", "subtle", "Subtle shadow effect"),
        t("elevated", "elevated", "Elevated shadow effect"),
        t("popover", "popover", "Popover shadow effect"),
        t("modal", "modal", "Modal shadow effect"),
      ],
    },
    variants: [
      t("primary", "primary", "Primary importance or hierarchy level"),
      t("secondary", "secondary", "Secondary importance or hierarchy level"),
      t("tertiary", "tertiary", "Tertiary importance or hierarchy level"),
      t("default", "default", "Default or standard level"),
      t("subtle", "subtle", "Low-emphasis level"),
      t("base", "base", "Base level in a scale"),
      t("destructive", "destructive", "Destructive or danger intent"),
      t("positive", "positive", "Positive or success meaning"),
      t("negative", "negative", "Negative or error meaning"),
      t("warning", "warning", "Warning meaning"),
      t("info", "info", "Informational meaning"),
      t("background", "background", "Background variation"),
      t("text", "text", "Text variation"),
      t("on", "on", "On state variation"),
      t("off", "off", "Off state variation"),
      t("strong", "strong", "Stronger variation"),
      t("compact", "compact", "Compact density variation"),
      t("spacious", "spacious", "Spacious density variation"),
    ],
    contexts: [
      t("inverse", "inverse", "Rendered on inverse or dark backgrounds"),
      t("on-media", "on-media", "Rendered on media or image backgrounds"),
      t("on-accent", "on-accent", "Rendered on accent-colored backgrounds"),
    ],
    states: [
      t("enabled", "enabled", "Default or enabled state"),
      t("hover", "hover", "Hover state"),
      t("pressed", "pressed", "Pressed or active state"),
      t("selected", "selected", "Selected state"),
      t("active", "active", "Active state"),
      t("disabled", "disabled", "Disabled state"),
      t("focus", "focus", "Focus state"),
      t("invalid", "invalid", "Invalid state"),
      t("visited", "visited", "Visited state"),
    ],
    emphasis: [
      t("deemphasized", "deemphasized", "Lower emphasis level"),
      t("base", "base", "Default emphasis level"),
      t("emphasized", "emphasized", "Stronger emphasis level"),
    ],
  },

  component: {
    components: [
      t("button", "button", "Standard button component"),
      t("icon-button", "icon-button", "Icon-only button component"),
      t("text-field", "text-field", "Text input field component"),
      t("search-field", "search-field", "Search input field component"),
      t("checkbox", "checkbox", "Checkbox input component"),
      t("radio", "radio", "Radio button input component"),
      t("switch", "switch", "Toggle switch input component"),
      t("slider", "slider", "Slider range input component"),
      t("tabs", "tabs", "Tabs navigation component"),
      t("nav-item", "nav-item", "Navigation item component"),
      t("dialog", "dialog", "Dialog or modal component"),
      t("tooltip", "tooltip", "Tooltip component"),
      t("toast", "toast", "Toast notification component"),
      t("list-cell", "list-cell", "List cell container component"),
      t("card", "card", "Card container component"),
    ],
    parts: [
      t("container", "container", "Main container element"),
      t("border", "border", "Border element"),
      t("field", "field", "Input field element"),
      t("label", "label", "Label text element"),
      t("title", "title", "Heading text element"),
      t("description", "description", "Supporting descriptive text"),
      t("placeholder", "placeholder", "Hint text shown when empty"),
      t("helper", "helper", "Guidance text under or near the field"),
      t("caption", "caption", "Small supporting text near media or content"),
      t("value", "value", "Displayed value or state element"),
      t("icon", "icon", "Icon element"),
      t("avatar", "avatar", "Identity image or initials"),
      t("thumbnail", "thumbnail", "Small preview image"),
      t("track", "track", "Path the thumb moves along"),
      t("thumb", "thumb", "Draggable piece on a track"),
      t("handle", "handle", "Drag target used to resize or reorder"),
      t("step", "step", "Discrete markers along a track"),
    ],
    properties: [
      t("background", "background", "Background color"),
      t("text", "text", "Text color"),
      t("icon", "icon", "Icon color"),
      t("border-color", "border-color", "Border color"),
      t("border-width", "border-width", "Border width"),
      t("radius", "radius", "Corner radius"),
      t("shadow", "shadow", "Shadow effect"),
      t("padding-x", "padding-x", "Horizontal padding"),
      t("padding-y", "padding-y", "Vertical padding"),
    ],
    variants: [
      t("primary", "primary", "Primary variant (main action)"),
      t("secondary", "secondary", "Secondary variant"),
      t("tertiary", "tertiary", "Tertiary variant"),
      t("subtle", "subtle", "Subtle low-emphasis variant"),
      t("outline", "outline", "Outline variant (bordered, transparent fill)"),
      t("ghost", "ghost", "Ghost variant (transparent, no border)"),
      t("destructive", "destructive", "Destructive variant"),
    ],
    states: [
      t("enabled", "enabled", "Default or enabled state"),
      t("hover", "hover", "Hover state"),
      t("pressed", "pressed", "Pressed or active state"),
      t("selected", "selected", "Selected state"),
      t("active", "active", "Active state"),
      t("disabled", "disabled", "Disabled state"),
      t("focus", "focus", "Focus state"),
      t("invalid", "invalid", "Invalid state"),
    ],
    contexts: [
      t("inverse", "inverse", "Rendered on inverse or dark backgrounds"),
      t("on-media", "on-media", "Rendered on media or image backgrounds"),
      t("on-accent", "on-accent", "Rendered on accent-colored backgrounds"),
    ],
  },
};
