const t = (value, label = value, description = "") => ({ value, label, description });

export const VOCABULARY = {
  prefix: {
    system: [],
    theme: [t("light"), t("dark"), t("hc", "High contrast")],
    domain: [],
  },

  primitive: {
    categories: [
      t("color"),
      t("space"),
      t("size"),
      t("radius"),
      t("border-width"),
      t("opacity"),
      t("shadow"),
      t("blur"),
      t("font-family"),
      t("font-size"),
      t("line-height"),
      t("font-weight"),
      t("letter-spacing"),
      t("duration"),
      t("easing"),
      t("layer"),
      t("breakpoint"),
    ],
    hues: [
      "white",
      "black",
      "gray",
      "blue",
      "red",
      "yellow",
      "green",
      "cyan",
      "indigo",
      "orange",
      "pink",
      "purple",
      "teal",
    ].map((v) => t(v)),
  },

  semantic: {
    domains: [
      "surface",
      "content",
      "separator",
      "action",
      "link",
      "focus",
      "status",
      "toggle",
      "range",
      "overlay",
      "accent",
      "constant",
      "type",
      "space",
      "size",
      "radius",
      "border-width",
      "shadow",
    ].map((v) => t(v)),
    objectsByDomain: {
      surface: ["background", "raised", "sunken", "canvas"].map((v) => t(v)),
      content: ["text", "icon", "placeholder"].map((v) => t(v)),
      action: ["bg", "text", "border", "icon"].map((v) => t(v)),
      status: ["positive", "negative", "warning", "info"].map((v) => t(v)),
      type: ["body", "heading", "mono"].map((v) => t(v)),
    },
    roles: ["primary", "secondary", "default", "subtle", "inverse"].map((v) => t(v)),
    contexts: ["inverse", "on-media", "on-accent"].map((v) => t(v)),
    states: ["default", "hover", "pressed", "selected", "active", "disabled", "focus", "invalid"].map((v) => t(v)),
    emphasis: ["weak", "default", "strong"].map((v) => t(v)),
  },

  component: {
    components: [
      "button",
      "icon-button",
      "text-field",
      "checkbox",
      "radio",
      "switch",
      "tabs",
      "nav-item",
      "card",
      "modal",
      "tooltip",
      "toast",
    ].map((v) => t(v)),
    parts: ["container", "label", "icon", "border", "track", "thumb", "field"].map((v) => t(v)),
    properties: ["bg", "text", "icon", "border-color", "border-width", "radius", "shadow", "padding-x", "padding-y"].map((v) => t(v)),
    variants: ["primary", "secondary", "tertiary", "subtle", "outline", "ghost", "destructive"].map((v) => t(v)),
    states: ["default", "hover", "pressed", "disabled", "focus", "invalid"].map((v) => t(v)),
    contexts: ["inverse", "on-media", "on-accent"].map((v) => t(v)),
  },
};

